export const BRAND = {
  name: "dlegaltech",
  tagline: "India's Most Trusted Digital Legal Consultancy Platform",
  phone: "+91-8603456708",
  whatsapp: "918603456708",
  email: "info@dlegaltech.com",
  website: "https://www.dlegaltech.com",
  primaryColor: "#0A346C",
  accentColor: "#ED931A",
};

// ─── SERVICES ──────────────────────────────────────────────────────────────

export const SERVICES = [
  // ── NGO / Non-Profit ──
  {
    id: "1",
    slug: "ngo-registration",
    category: "ngo",
    name: "NGO Registration",
    icon: "🏛️",
    shortDescription: "Register your NGO/Trust under the Societies Registration Act or Indian Trusts Act with complete compliance.",
    description: "Complete NGO registration services including Trust, Society, and Section 8 Company formation with all government compliance.",
    price: 4999,
    originalPrice: 7999,
    timeline: "7-10 working days",
    badge: "Most Popular",
    seoTitle: "NGO Registration Online India | dlegaltech",
    seoDescription: "Register your NGO online in India starting at ₹4,999. Trust, Society & Section 8 Company registration by expert legal team.",
    benefits: ["Certificate of Incorporation", "PAN & TAN Registration", "Bank Account Opening Support", "80G & 12A Guidance"],
    documents: ["Aadhar Card of all members", "PAN Card", "Address Proof", "Passport Size Photos", "Registered Office Address Proof"],
    process: [
      { step: 1, title: "Submit Application", desc: "Fill online form with member details" },
      { step: 2, title: "Document Review", desc: "Our experts verify all documents" },
      { step: 3, title: "Government Filing", desc: "We file with concerned authority" },
      { step: 4, title: "Certificate Issued", desc: "Receive digital certificate" },
    ],
    faqs: [
      { q: "What is the minimum number of members for NGO registration?", a: "For Society registration, minimum 7 members are required. For Trust, minimum 2 trustees are needed." },
      { q: "Can an NGO earn profit?", a: "No, NGOs cannot distribute profits among members. Any surplus must be used for the stated objectives." },
      { q: "How long does NGO registration take?", a: "Generally 7-10 working days after complete document submission and payment." },
    ],
    relatedServices: ["12a-80g-registration", "fcra-registration", "section-8-company"],
  },
  {
    id: "2",
    slug: "12a-80g-registration",
    category: "ngo",
    name: "12A & 80G Registration",
    icon: "📋",
    shortDescription: "Get tax exemption for your NGO under Section 12A and enable donors to claim tax benefits under 80G.",
    description: "Secure tax exemption status for your NGO with 12A registration and attract more donations with 80G certification.",
    price: 3999,
    originalPrice: 5999,
    timeline: "30-45 working days",
    badge: "Tax Benefit",
    seoTitle: "12A 80G Registration Online India | dlegaltech",
    seoDescription: "Get NGO tax exemption with 12A & 80G registration starting at ₹3,999. Enable donors to claim 50% tax deduction.",
    benefits: ["Income Tax Exemption", "Donor Tax Benefits", "Government Grants Eligibility", "CSR Funding Access"],
    documents: ["NGO Registration Certificate", "Trust Deed / MoA", "Audited Financial Statements", "Activity Report", "PAN Card of NGO"],
    process: [
      { step: 1, title: "Eligibility Check", desc: "Verify NGO eligibility criteria" },
      { step: 2, title: "Application Prep", desc: "Prepare Form 10A/10AB" },
      { step: 3, title: "IT Department Filing", desc: "Submit to Income Tax authorities" },
      { step: 4, title: "Certificate Received", desc: "Get 12A & 80G certificates" },
    ],
    faqs: [
      { q: "What is the difference between 12A and 80G?", a: "12A gives tax exemption to the NGO itself on its income. 80G allows donors to claim tax deductions on their donations." },
      { q: "Is 12A registration mandatory for NGOs?", a: "Not mandatory, but highly recommended as it exempts NGO income from tax and makes the organization eligible for government grants." },
    ],
    relatedServices: ["ngo-registration", "fcra-registration", "csr-funding"],
  },
  {
    id: "3",
    slug: "section-8-company",
    category: "ngo",
    name: "Section 8 Company",
    icon: "🏢",
    shortDescription: "Incorporate a Section 8 Company (Non-Profit Organization) under Companies Act 2013 with MCA registration.",
    description: "Section 8 Company is the most credible form of NGO in India, regulated by MCA with highest transparency and governance.",
    price: 6999,
    originalPrice: 9999,
    timeline: "15-20 working days",
    badge: "High Credibility",
    seoTitle: "Section 8 Company Registration India | dlegaltech",
    seoDescription: "Register Section 8 Non-Profit Company online starting at ₹6,999. MCA registration, most credible NGO form in India.",
    benefits: ["MCA Registered", "Limited Liability", "No Minimum Capital", "Government Grant Eligible", "Foreign Funding (FCRA)"],
    documents: ["Director KYC (Aadhar + PAN)", "Address Proof of Directors", "Registered Office Proof", "Digital Signature Certificate (DSC)", "Objectives/MoA Draft"],
    process: [
      { step: 1, title: "Name Approval", desc: "Apply for company name via MCA portal" },
      { step: 2, title: "DIN & DSC", desc: "Director Identification Number & Digital Signature" },
      { step: 3, title: "MOA & AOA Filing", desc: "File incorporation documents with MCA" },
      { step: 4, title: "Certificate of Incorporation", desc: "Receive CoI from MCA" },
    ],
    faqs: [
      { q: "What is a Section 8 Company?", a: "A Section 8 Company is a non-profit organization incorporated under Section 8 of the Companies Act 2013, formed for promoting arts, science, sports, education, social welfare, etc." },
      { q: "Can a Section 8 Company receive foreign donations?", a: "Yes, after obtaining FCRA registration, a Section 8 Company can receive foreign contributions." },
    ],
    relatedServices: ["ngo-registration", "fcra-registration", "12a-80g-registration"],
  },
  {
    id: "4",
    slug: "fcra-registration",
    category: "ngo",
    name: "FCRA Registration",
    icon: "🌐",
    shortDescription: "Get FCRA license to legally receive foreign contributions and donations for your NGO activities.",
    description: "Foreign Contribution (Regulation) Act registration to receive donations from foreign nationals, organizations, and governments.",
    price: 8999,
    originalPrice: 12999,
    timeline: "3-6 months",
    badge: "Foreign Funding",
    seoTitle: "FCRA Registration Online India | dlegaltech",
    seoDescription: "Get FCRA registration for your NGO to receive foreign donations legally. Complete assistance starting at ₹8,999.",
    benefits: ["Foreign Donation Legal", "FCRA Bank Account", "International Credibility", "Expanded Funding Sources"],
    documents: ["NGO Registration Certificate", "12A & 80G Certificates", "3 Year Audited Accounts", "Board Resolution", "Activity Report (Last 3 years)"],
    process: [
      { step: 1, title: "Eligibility Assessment", desc: "Verify 3-year existence and activities" },
      { step: 2, title: "Online Application", desc: "File FCRA application on MHA portal" },
      { step: 3, title: "Police Verification", desc: "Background check of key office bearers" },
      { step: 4, title: "FCRA Granted", desc: "Receive FCRA registration certificate" },
    ],
    faqs: [
      { q: "Who can apply for FCRA?", a: "NGOs that have been registered for at least 3 years and have spent minimum ₹15 lakh on activities can apply for FCRA." },
      { q: "What is the FCRA bank account requirement?", a: "All foreign contributions must be received in a designated FCRA bank account, typically at SBI New Delhi main branch." },
    ],
    relatedServices: ["ngo-registration", "12a-80g-registration", "section-8-company"],
  },
  {
    id: "5",
    slug: "csr-funding",
    category: "ngo",
    name: "CSR Funding Assistance",
    icon: "💰",
    shortDescription: "Connect your NGO with corporates for CSR funding. End-to-end proposal writing and compliance support.",
    description: "Complete CSR funding assistance — from identifying potential donors to writing compelling proposals and maintaining compliance.",
    price: 9999,
    originalPrice: 14999,
    timeline: "Ongoing service",
    badge: "High Value",
    seoTitle: "CSR Funding for NGO India | dlegaltech",
    seoDescription: "Get CSR funding for your NGO. Expert proposal writing, corporate matching, and compliance support. Connect with 500+ CSR donors.",
    benefits: ["Corporate Connections", "Proposal Writing", "CSR Compliance", "Form CSR-1 Filing", "Impact Reporting"],
    documents: ["NGO Registration", "12A & 80G Certificates", "FCRA (if applicable)", "Audited Accounts", "Project Proposal"],
    process: [
      { step: 1, title: "NGO Profile Creation", desc: "Create compelling NGO dossier" },
      { step: 2, title: "CSR-1 Filing", desc: "Register on MCA CSR portal" },
      { step: 3, title: "Corporate Matching", desc: "Connect with relevant CSR committees" },
      { step: 4, title: "Proposal & Follow-up", desc: "Submit and track applications" },
    ],
    faqs: [
      { q: "What is CSR-1 form?", a: "CSR-1 is a mandatory form for NGOs to register on the MCA portal to receive CSR funds from companies. It establishes the NGO's credibility." },
      { q: "Which companies provide CSR funding?", a: "Companies with net worth ≥₹500 crore, or turnover ≥₹1000 crore, or net profit ≥₹5 crore must spend 2% of average net profit on CSR." },
    ],
    relatedServices: ["ngo-registration", "12a-80g-registration", "fcra-registration"],
  },
  {
    id: "6",
    slug: "niti-aayog-registration",
    category: "ngo",
    name: "NITI Aayog Registration",
    icon: "🏅",
    shortDescription: "Register your NGO on NITI Aayog's Darpan portal to access government schemes and grants.",
    description: "NITI Aayog Darpan registration is mandatory for NGOs to receive central government grants and access welfare schemes.",
    price: 1999,
    originalPrice: 3499,
    timeline: "3-5 working days",
    badge: "Government Grant",
    seoTitle: "NITI Aayog NGO Registration | Darpan Portal | dlegaltech",
    seoDescription: "Register NGO on NITI Aayog Darpan portal starting at ₹1,999. Mandatory for central government grants. Expert assistance.",
    benefits: ["Government Grants Access", "Darpan Unique ID", "Central Scheme Eligibility", "Enhanced Credibility"],
    documents: ["NGO Registration Certificate", "PAN of NGO", "Bank Account Details", "12A Certificate (if available)", "Objectives Document"],
    process: [
      { step: 1, title: "Account Creation", desc: "Create account on NITI Aayog Darpan portal" },
      { step: 2, title: "NGO Profile", desc: "Fill complete organization profile" },
      { step: 3, title: "Document Upload", desc: "Upload all required certificates" },
      { step: 4, title: "Darpan ID Issued", desc: "Receive unique Darpan registration ID" },
    ],
    faqs: [
      { q: "What is NITI Aayog Darpan?", a: "Darpan is an online portal maintained by NITI Aayog where NGOs register to access central government grants and schemes." },
      { q: "Is Darpan registration mandatory?", a: "Yes, Darpan registration with a Unique ID is mandatory for receiving grants from central government ministries and PSUs." },
    ],
    relatedServices: ["ngo-registration", "12a-80g-registration", "csr-funding"],
  },
  // ── Business Registration ──
  {
    id: "7",
    slug: "private-limited-company",
    category: "business",
    name: "Private Limited Company",
    icon: "🏗️",
    shortDescription: "Register your Private Limited Company with MCA. Most preferred structure for startups and growing businesses.",
    description: "Complete Pvt Ltd company incorporation — name approval, DIN, DSC, SPICe+ filing, and Certificate of Incorporation.",
    price: 5999,
    originalPrice: 8999,
    timeline: "10-15 working days",
    badge: "Most Trusted",
    seoTitle: "Private Limited Company Registration India | dlegaltech",
    seoDescription: "Register Private Limited Company online starting at ₹5,999. SPICe+ MCA filing, DIN, DSC included. Expert assistance.",
    benefits: ["Separate Legal Entity", "Limited Liability", "Easy Funding", "Tax Benefits", "Brand Credibility"],
    documents: ["Director PAN & Aadhar", "Address Proof", "Registered Office Proof", "MOA & AOA Draft", "DSC Application"],
    process: [
      { step: 1, title: "Name Reservation", desc: "Apply for company name via RUN/SPICE+" },
      { step: 2, title: "DIN & DSC", desc: "Obtain Director Identification Numbers" },
      { step: 3, title: "Incorporation Filing", desc: "File SPICe+ form with MCA" },
      { step: 4, title: "CoI Issued", desc: "Certificate of Incorporation from MCA" },
    ],
    faqs: [
      { q: "What is the minimum capital for Pvt Ltd?", a: "There is no minimum paid-up capital requirement for Private Limited Company registration in India." },
      { q: "How many directors are needed?", a: "Minimum 2 directors are required for a Private Limited Company, with at least one being a resident Indian." },
    ],
    relatedServices: ["llp-registration", "gst-registration", "trademark-registration"],
  },
  {
    id: "8",
    slug: "opc-registration",
    category: "business",
    name: "One Person Company (OPC)",
    icon: "👤",
    shortDescription: "Start a One Person Company — get corporate benefits with single founder. Ideal for solo entrepreneurs.",
    description: "OPC gives a single entrepreneur full corporate status with limited liability, separate legal entity, and easy compliance.",
    price: 4999,
    originalPrice: 7999,
    timeline: "10-15 working days",
    badge: "Solo Founder",
    seoTitle: "OPC Registration Online India | One Person Company | dlegaltech",
    seoDescription: "Register One Person Company online starting at ₹4,999. Corporate benefits for solo entrepreneurs. MCA compliant.",
    benefits: ["Single Founder", "Limited Liability", "No Partner Needed", "Corporate Credibility", "Easy Compliance"],
    documents: ["Founder PAN & Aadhar", "Address Proof", "Registered Office Proof", "Nominee Details", "DSC Application"],
    process: [
      { step: 1, title: "Name Approval", desc: "Reserve OPC name with MCA" },
      { step: 2, title: "DIN & DSC", desc: "Director Identification Number & signature" },
      { step: 3, title: "SPICe+ Filing", desc: "File incorporation documents" },
      { step: 4, title: "Certificate Issued", desc: "Receive OPC Certificate of Incorporation" },
    ],
    faqs: [
      { q: "Who can form an OPC?", a: "Only a natural person who is an Indian citizen and resident in India can incorporate an OPC. One person can be a member of only one OPC." },
      { q: "Can an OPC be converted to Pvt Ltd?", a: "Yes, an OPC must mandatorily convert to a Private Limited Company when paid-up capital exceeds ₹50 lakhs or turnover exceeds ₹2 crore." },
    ],
    relatedServices: ["private-limited-company", "llp-registration", "gst-registration"],
  },
  {
    id: "9",
    slug: "llp-registration",
    category: "business",
    name: "LLP Registration",
    icon: "🤝",
    shortDescription: "Register a Limited Liability Partnership — flexible structure with limited liability for all partners.",
    description: "LLP combines benefits of partnership and company — limited liability, flexible management, lower compliance costs.",
    price: 4999,
    originalPrice: 7499,
    timeline: "10-15 working days",
    badge: "Low Compliance",
    seoTitle: "LLP Registration Online India | Limited Liability Partnership | dlegaltech",
    seoDescription: "Register LLP online starting at ₹4,999. Limited liability for all partners, flexible management. Expert MCA filing.",
    benefits: ["Limited Liability", "Flexible Management", "Lower Compliance", "No Minimum Capital", "Separate Legal Entity"],
    documents: ["Partner PAN & Aadhar", "Address Proof", "Registered Office Proof", "LLP Agreement Draft", "DSC of Partners"],
    process: [
      { step: 1, title: "Name Approval", desc: "Reserve LLP name via RUN-LLP" },
      { step: 2, title: "DIN & DSC", desc: "Designated Partner Identification Number" },
      { step: 3, title: "FiLLiP Filing", desc: "File incorporation form with MCA" },
      { step: 4, title: "LLP Agreement", desc: "Execute and file LLP agreement" },
    ],
    faqs: [
      { q: "Minimum partners in LLP?", a: "Minimum 2 designated partners are required to form an LLP. At least one must be a resident Indian." },
      { q: "Is annual filing mandatory for LLP?", a: "Yes, LLPs must file Form 8 (Statement of Account) and Form 11 (Annual Return) each year with MCA." },
    ],
    relatedServices: ["private-limited-company", "partnership-firm", "gst-registration"],
  },
  {
    id: "10",
    slug: "partnership-firm",
    category: "business",
    name: "Partnership Firm",
    icon: "📑",
    shortDescription: "Register a Partnership Firm under the Partnership Act 1932. Simple structure for small businesses.",
    description: "Partnership firm registration with deed drafting, notarization, and registration with Registrar of Firms.",
    price: 2499,
    originalPrice: 3999,
    timeline: "5-7 working days",
    badge: "Simple Setup",
    seoTitle: "Partnership Firm Registration India | dlegaltech",
    seoDescription: "Register Partnership Firm online starting at ₹2,499. Expert deed drafting & Registrar filing. Simple business setup.",
    benefits: ["Simple Structure", "Easy Setup", "Flexible Agreement", "Low Cost", "Shared Responsibility"],
    documents: ["Partner PAN & Aadhar", "Address Proof", "Business Address Proof", "Partnership Deed Draft"],
    process: [
      { step: 1, title: "Deed Drafting", desc: "Draft Partnership Deed with agreed terms" },
      { step: 2, title: "Stamp Duty", desc: "Pay applicable stamp duty on deed" },
      { step: 3, title: "Notarization", desc: "Notarize the partnership deed" },
      { step: 4, title: "ROF Filing", desc: "File with Registrar of Firms (optional but recommended)" },
    ],
    faqs: [
      { q: "Is partnership registration mandatory?", a: "Registration is not mandatory but highly recommended as it gives the firm legal standing to sue and be sued in court." },
      { q: "Can a partnership firm be converted to LLP?", a: "Yes, a registered partnership firm can be converted to LLP by filing Form 17 with MCA." },
    ],
    relatedServices: ["llp-registration", "gst-registration", "trademark-registration"],
  },
  {
    id: "11",
    slug: "startup-india",
    category: "business",
    name: "Startup India Registration",
    icon: "🚀",
    shortDescription: "Register under Startup India to access DPIIT recognition, tax exemptions, and government schemes.",
    description: "DPIIT Startup India recognition unlocks tax benefits (3-year exemption), easy compliance, and access to ₹10,000 Cr fund.",
    price: 2999,
    originalPrice: 4999,
    timeline: "7-10 working days",
    badge: "Tax Exemption",
    seoTitle: "Startup India DPIIT Registration | dlegaltech",
    seoDescription: "Get DPIIT Startup India recognition starting at ₹2,999. 3-year tax exemption, reduced compliance, government schemes access.",
    benefits: ["DPIIT Recognition", "3-Year Tax Exemption", "Patent Fee Rebate", "Self-Certification", "₹10,000 Cr Fund Access"],
    documents: ["Company/LLP Registration", "Incorporation Certificate", "PAN", "Website/Pitch Deck", "Brief Business Description"],
    process: [
      { step: 1, title: "Entity Check", desc: "Verify eligibility (Pvt Ltd/OPC/LLP/Partnership)" },
      { step: 2, title: "DPIIT Application", desc: "Apply on Startup India portal with business details" },
      { step: 3, title: "Document Submission", desc: "Upload incorporation and business documents" },
      { step: 4, title: "Recognition Certificate", desc: "Receive DPIIT recognition number" },
    ],
    faqs: [
      { q: "Who qualifies as a Startup?", a: "An entity up to 10 years old with annual turnover under ₹100 crore, working towards innovation/improvement of products/services." },
      { q: "What tax benefits does Startup India give?", a: "DPIIT recognized startups get 100% tax exemption for 3 consecutive years out of first 10 years, subject to conditions." },
    ],
    relatedServices: ["private-limited-company", "gst-registration", "trademark-registration"],
  },
  {
    id: "12",
    slug: "sole-proprietorship",
    category: "business",
    name: "Sole Proprietorship",
    icon: "🧑‍💼",
    shortDescription: "Set up a Sole Proprietorship business — simplest business structure with full ownership and control.",
    description: "Complete sole proprietorship setup including GST registration, Udyam registration, and bank account opening support.",
    price: 1999,
    originalPrice: 3499,
    timeline: "3-5 working days",
    badge: "Quickest",
    seoTitle: "Sole Proprietorship Registration India | dlegaltech",
    seoDescription: "Set up Sole Proprietorship starting at ₹1,999. GST + Udyam registration, bank account support. Fastest business setup.",
    benefits: ["Full Ownership", "Minimal Compliance", "Easy to Start", "Low Cost", "Direct Tax Filing"],
    documents: ["Owner PAN & Aadhar", "Address Proof", "Business Address Proof", "Bank Account Details"],
    process: [
      { step: 1, title: "GST Registration", desc: "Get GSTIN for business identity" },
      { step: 2, title: "Udyam Registration", desc: "MSME registration for benefits" },
      { step: 3, title: "Bank Account", desc: "Open current account in business name" },
      { step: 4, title: "Trade License", desc: "Obtain local trade license (if required)" },
    ],
    faqs: [
      { q: "Is sole proprietorship legally recognized?", a: "Yes, but the business is not a separate legal entity. The owner has unlimited personal liability for business debts." },
      { q: "What taxes does a sole proprietor pay?", a: "Sole proprietors file income tax as individuals using ITR-3 or ITR-4 (for presumptive taxation)." },
    ],
    relatedServices: ["gst-registration", "msme-udyam", "trademark-registration"],
  },
  // ── Tax & Compliance ──
  {
    id: "13",
    slug: "gst-registration",
    category: "tax",
    name: "GST Registration",
    icon: "📊",
    shortDescription: "Register for Goods and Services Tax with hassle-free online process and get GSTIN within 3-5 days.",
    description: "Complete GST registration for businesses, NGOs, and professionals with ongoing compliance support.",
    price: 1499,
    originalPrice: 2499,
    timeline: "3-5 working days",
    badge: "Quick Process",
    seoTitle: "GST Registration Online India | dlegaltech",
    seoDescription: "Get GST registration online in 3-5 days starting at ₹1,499. Expert assistance for businesses, NGOs & professionals.",
    benefits: ["GSTIN Issued", "Input Tax Credit", "Legal Business Recognition", "Interstate Trade Enabled"],
    documents: ["Aadhar Card", "PAN Card", "Business Address Proof", "Bank Account Details", "Business Photographs"],
    process: [
      { step: 1, title: "Document Collection", desc: "Submit required KYC documents" },
      { step: 2, title: "Form Filling", desc: "File REG-01 on GST portal" },
      { step: 3, title: "ARN Generated", desc: "Application Reference Number issued" },
      { step: 4, title: "GSTIN Received", desc: "GST Identification Number issued" },
    ],
    faqs: [
      { q: "Who needs to register for GST?", a: "Businesses with turnover above ₹40 lakhs (₹20 lakhs for services) must register for GST. Inter-state suppliers must register regardless of turnover." },
      { q: "Is GST registration mandatory for NGOs?", a: "NGOs providing taxable services with turnover above threshold must register. Services like education, healthcare are generally exempt." },
    ],
    relatedServices: ["ngo-registration", "private-limited-company", "trademark-registration"],
  },
  {
    id: "14",
    slug: "gst-return-filing",
    category: "tax",
    name: "GST Return Filing",
    icon: "📝",
    shortDescription: "Monthly, quarterly, and annual GST return filing (GSTR-1, GSTR-3B, GSTR-9) by tax experts.",
    description: "Hassle-free GST return filing with reconciliation, input tax credit optimization, and compliance management.",
    price: 999,
    originalPrice: 1999,
    timeline: "Same day",
    badge: "Monthly Service",
    seoTitle: "GST Return Filing Online India | dlegaltech",
    seoDescription: "GST return filing by experts starting at ₹999/month. GSTR-1, GSTR-3B, GSTR-9 filing with ITC reconciliation.",
    benefits: ["No Penalty", "ITC Optimization", "Reconciliation", "Expert Review", "Timely Filing"],
    documents: ["Sales Invoices", "Purchase Invoices", "Bank Statements", "Previous Return Copy"],
    process: [
      { step: 1, title: "Data Collection", desc: "Gather sales and purchase data" },
      { step: 2, title: "Reconciliation", desc: "Reconcile books with GST portal" },
      { step: 3, title: "Return Preparation", desc: "Prepare GSTR-1 and GSTR-3B" },
      { step: 4, title: "Filing & Acknowledgment", desc: "File returns and share ARN" },
    ],
    faqs: [
      { q: "What is GSTR-3B?", a: "GSTR-3B is a monthly self-declaration return that summarizes outward and inward supplies, ITC claimed, and tax paid." },
      { q: "What happens if GST return is filed late?", a: "Late filing attracts interest at 18% per annum on tax due, plus late fees of ₹50/day (₹25/day for nil return)." },
    ],
    relatedServices: ["gst-registration", "income-tax-return", "private-limited-company"],
  },
  {
    id: "15",
    slug: "income-tax-return",
    category: "tax",
    name: "Income Tax Return (ITR)",
    icon: "🧾",
    shortDescription: "File your Income Tax Return accurately and on time. Individual, business, and NGO ITR filing.",
    description: "Expert ITR filing for individuals, sole proprietors, companies, LLPs, NGOs, and trusts with full compliance.",
    price: 1499,
    originalPrice: 2499,
    timeline: "2-3 working days",
    badge: "Annual Filing",
    seoTitle: "Income Tax Return Filing Online India | dlegaltech",
    seoDescription: "File ITR online starting at ₹1,499. Individual, business, NGO, and trust ITR filing by CA-qualified experts.",
    benefits: ["Accurate Filing", "Maximum Deductions", "No Notices", "Carry Forward Losses", "Refund Processing"],
    documents: ["Form 16 / Income Proof", "Bank Statements", "Investment Proofs", "Property Documents (if applicable)", "Previous ITR"],
    process: [
      { step: 1, title: "Income Assessment", desc: "Review all income sources and deductions" },
      { step: 2, title: "Form Selection", desc: "Choose correct ITR form (ITR-1 to ITR-7)" },
      { step: 3, title: "Return Preparation", desc: "Prepare return with all schedules" },
      { step: 4, title: "Filing & Verification", desc: "E-file and verify via Aadhar OTP" },
    ],
    faqs: [
      { q: "Who must file ITR?", a: "Every individual with taxable income above ₹2.5 lakh (₹3 lakh for senior citizens) must file ITR. Also mandatory for claiming refunds." },
      { q: "What is the due date for ITR filing?", a: "For individuals: July 31. For businesses requiring audit: October 31. Belated return can be filed by December 31." },
    ],
    relatedServices: ["gst-registration", "gst-return-filing", "private-limited-company"],
  },
  {
    id: "16",
    slug: "msme-udyam",
    category: "tax",
    name: "MSME / Udyam Registration",
    icon: "🏭",
    shortDescription: "Register under MSME Udyam portal to access government subsidies, priority sector lending, and schemes.",
    description: "Udyam registration (new MSME registration) gives priority sector credit, government tender eligibility, and subsidies.",
    price: 999,
    originalPrice: 1999,
    timeline: "1-2 working days",
    badge: "Government Benefits",
    seoTitle: "MSME Udyam Registration Online India | dlegaltech",
    seoDescription: "Get MSME Udyam registration starting at ₹999. Access government subsidies, priority lending, tender eligibility.",
    benefits: ["Priority Sector Credit", "Government Tenders", "Subsidies & Schemes", "Collateral-Free Loans", "Tax Benefits"],
    documents: ["Aadhar of Proprietor/Director", "PAN of Business", "GSTIN", "Bank Account Details", "Business Activity Details"],
    process: [
      { step: 1, title: "Eligibility Check", desc: "Verify business investment & turnover criteria" },
      { step: 2, title: "Udyam Portal", desc: "Register on udyamregistration.gov.in" },
      { step: 3, title: "Aadhar OTP Verification", desc: "Verify with Aadhar-linked mobile" },
      { step: 4, title: "Udyam Certificate", desc: "Download Udyam registration certificate" },
    ],
    faqs: [
      { q: "What is the investment limit for MSME?", a: "Micro: Investment ≤₹1 crore, Turnover ≤₹5 crore. Small: ≤₹10 crore, ≤₹50 crore. Medium: ≤₹50 crore, ≤₹250 crore." },
      { q: "Is old MSME registration (EM-II/UAM) still valid?", a: "Old registrations are migrated. New Udyam registration is mandatory for all MSMEs from July 2020." },
    ],
    relatedServices: ["gst-registration", "sole-proprietorship", "fssai-license"],
  },
  // ── Trademark & IP ──
  {
    id: "17",
    slug: "trademark-registration",
    category: "ip",
    name: "Trademark Registration",
    icon: "™️",
    shortDescription: "Protect your brand identity with trademark registration under the Trade Marks Act 1999.",
    description: "Secure your brand name, logo, and tagline with trademark registration. Protect your intellectual property legally.",
    price: 5999,
    originalPrice: 8999,
    timeline: "1-2 years (final), TM symbol in 2-3 days",
    badge: "Brand Protection",
    seoTitle: "Trademark Registration Online India | dlegaltech",
    seoDescription: "Register your trademark online starting at ₹5,999. Protect brand name, logo & tagline. TM symbol usage from day 1.",
    benefits: ["Brand Protection", "Legal Rights", "TM Symbol Usage", "Infringement Action", "Asset Creation"],
    documents: ["Applicant ID Proof", "Logo/Brand Name (JPG)", "Goods/Services Description", "POA (Power of Attorney)", "MSME Certificate (if applicable)"],
    process: [
      { step: 1, title: "Trademark Search", desc: "Check availability and conflicts" },
      { step: 2, title: "Application Filing", desc: "File TM-A with IP India" },
      { step: 3, title: "TM Symbol Allowed", desc: "Use ™ immediately after filing" },
      { step: 4, title: "® Symbol", desc: "After registration approval (12-18 months)" },
    ],
    faqs: [
      { q: "How long does trademark registration take?", a: "After filing, you can use the ™ symbol immediately. Full ® registration takes 12-24 months subject to objections and oppositions." },
      { q: "What can be trademarked?", a: "Brand names, logos, taglines, product names, sounds, colors, and shapes can be registered as trademarks." },
    ],
    relatedServices: ["copyright-registration", "private-limited-company", "gst-registration"],
  },
  {
    id: "18",
    slug: "trademark-objection",
    category: "ip",
    name: "Trademark Objection Reply",
    icon: "⚖️",
    shortDescription: "Expert reply to trademark examination objections. Protect your application from refusal.",
    description: "Professional drafting of examination report reply with legal arguments, case laws, and evidence to overcome trademark objections.",
    price: 3999,
    originalPrice: 5999,
    timeline: "5-7 working days",
    badge: "Expert Reply",
    seoTitle: "Trademark Objection Reply India | dlegaltech",
    seoDescription: "Expert trademark objection reply starting at ₹3,999. Professional legal arguments, case citations to overcome refusal.",
    benefits: ["Expert Legal Reply", "Case Law Support", "Evidence Compilation", "Follow-Up Hearing", "High Success Rate"],
    documents: ["Trademark Application Number", "Examination Report", "Evidence of Use (if available)", "Affidavit (if required)"],
    process: [
      { step: 1, title: "Report Analysis", desc: "Review examination report objections" },
      { step: 2, title: "Strategy Planning", desc: "Build strongest legal arguments" },
      { step: 3, title: "Reply Drafting", desc: "Draft detailed response with evidence" },
      { step: 4, title: "Filing & Follow-up", desc: "Submit reply and track hearing" },
    ],
    faqs: [
      { q: "What is a trademark examination report?", a: "When trademark application is filed, the TM Registry examines it and may raise objections. You must reply within 30 days." },
      { q: "What happens if no reply is filed?", a: "If no reply is filed within the prescribed time, the application is abandoned and all fees are forfeited." },
    ],
    relatedServices: ["trademark-registration", "copyright-registration", "patent-filing"],
  },
  {
    id: "19",
    slug: "copyright-registration",
    category: "ip",
    name: "Copyright Registration",
    icon: "©️",
    shortDescription: "Protect your creative work — books, music, software, artwork — with official copyright registration.",
    description: "Copyright registration for literary, artistic, musical, dramatic works, computer programs, and cinematographic films.",
    price: 3499,
    originalPrice: 5499,
    timeline: "2-3 months",
    badge: "Creative Protection",
    seoTitle: "Copyright Registration Online India | dlegaltech",
    seoDescription: "Register copyright for books, music, software, artwork starting at ₹3,499. Protect creative works legally in India.",
    benefits: ["Legal Protection", "Ownership Proof", "Infringement Action", "Licensing Rights", "Asset Creation"],
    documents: ["Applicant ID Proof", "Work Sample (3 copies)", "Power of Attorney", "Statement of Particulars", "NOC (if applicable)"],
    process: [
      { step: 1, title: "Application Prep", desc: "Prepare Form XIV with work details" },
      { step: 2, title: "Work Submission", desc: "Submit 3 copies of the work" },
      { step: 3, title: "Diary Number", desc: "Receive diary number and wait period" },
      { step: 4, title: "Certificate Issued", desc: "Receive copyright registration certificate" },
    ],
    faqs: [
      { q: "What works can be copyrighted?", a: "Literary works (books, articles, software), artistic works (paintings, photos), musical works, films, broadcasts, and sound recordings." },
      { q: "How long does copyright last?", a: "For most works, copyright lasts for the lifetime of the author plus 60 years. For films and broadcasts, it's 60 years from publication." },
    ],
    relatedServices: ["trademark-registration", "patent-filing", "private-limited-company"],
  },
  {
    id: "20",
    slug: "patent-filing",
    category: "ip",
    name: "Patent Filing",
    icon: "🔬",
    shortDescription: "File a provisional or complete patent specification to protect your invention in India.",
    description: "Complete patent filing assistance — prior art search, specification drafting, filing with Indian Patent Office, and prosecution.",
    price: 14999,
    originalPrice: 24999,
    timeline: "Provisional: 2-3 days | Complete: 15-20 days",
    badge: "Invention Protection",
    seoTitle: "Patent Filing India | Provisional & Complete Patent | dlegaltech",
    seoDescription: "File patent in India starting at ₹14,999. Provisional & complete specification drafting. Expert patent attorneys.",
    benefits: ["Invention Protection", "20-Year Monopoly", "Licensing Revenue", "Investor Attraction", "Market Advantage"],
    documents: ["Invention Disclosure", "Technical Drawings", "Claims Draft", "Applicant ID Proof", "Assignment Deed (if applicable)"],
    process: [
      { step: 1, title: "Prior Art Search", desc: "Search existing patents for novelty" },
      { step: 2, title: "Specification Drafting", desc: "Draft claims and description" },
      { step: 3, title: "IPO Filing", desc: "File with Indian Patent Office" },
      { step: 4, title: "Application Number", desc: "Receive patent application number" },
    ],
    faqs: [
      { q: "What is a provisional patent?", a: "A provisional application establishes a priority date without complete claims. You have 12 months to file a complete specification." },
      { q: "How long does a patent last?", a: "A granted patent is valid for 20 years from the date of filing, subject to annual renewal fees." },
    ],
    relatedServices: ["trademark-registration", "copyright-registration", "private-limited-company"],
  },
  // ── Licenses & Permits ──
  {
    id: "21",
    slug: "fssai-license",
    category: "licenses",
    name: "FSSAI Food License",
    icon: "🍎",
    shortDescription: "Get FSSAI Basic Registration, State License, or Central License for your food business.",
    description: "FSSAI Food Safety and Standards Authority of India license for food manufacturers, traders, restaurants, and e-commerce food businesses.",
    price: 1999,
    originalPrice: 3499,
    timeline: "7-10 working days",
    badge: "Food Business",
    seoTitle: "FSSAI Food License Registration India | dlegaltech",
    seoDescription: "Get FSSAI food license starting at ₹1,999. Basic registration, State & Central license. Mandatory for all food businesses.",
    benefits: ["Legal Compliance", "Consumer Trust", "Avoid Penalties", "Business Expansion", "Export Eligibility"],
    documents: ["ID & Address Proof", "Business Address Proof", "Photo of Business Premises", "Water Testing Report", "Business Nature Declaration"],
    process: [
      { step: 1, title: "License Type", desc: "Determine Basic/State/Central based on turnover" },
      { step: 2, title: "Application Filing", desc: "Apply on FoSCoS portal" },
      { step: 3, title: "Inspection (if required)", desc: "Premises inspection by authority" },
      { step: 4, title: "License Issued", desc: "Receive FSSAI license number" },
    ],
    faqs: [
      { q: "Which FSSAI license do I need?", a: "Basic registration for turnover ≤₹12 lakh. State license for ₹12 lakh to ₹20 crore. Central license for turnover above ₹20 crore." },
      { q: "Is FSSAI mandatory for restaurants?", a: "Yes, every food business operator (restaurant, caterer, manufacturer, trader) must have a valid FSSAI license." },
    ],
    relatedServices: ["gst-registration", "msme-udyam", "trademark-registration"],
  },
  {
    id: "22",
    slug: "iec-code",
    category: "licenses",
    name: "Import Export Code (IEC)",
    icon: "✈️",
    shortDescription: "Get Import Export Code from DGFT — mandatory for all import/export businesses in India.",
    description: "IEC is a 10-digit code issued by DGFT mandatory for any business or person importing or exporting goods and services.",
    price: 1999,
    originalPrice: 2999,
    timeline: "2-3 working days",
    badge: "International Trade",
    seoTitle: "Import Export Code IEC Registration India | dlegaltech",
    seoDescription: "Get IEC code from DGFT starting at ₹1,999. Mandatory for import/export business. 2-3 day processing.",
    benefits: ["Import/Export Legal", "No Renewal Needed", "Customs Clearance", "Foreign Remittance", "Global Business"],
    documents: ["PAN Card", "Aadhar Card", "Bank Account Details", "Cancel Cheque", "Business Address Proof"],
    process: [
      { step: 1, title: "DGFT Account", desc: "Create account on DGFT portal" },
      { step: 2, title: "Application Form", desc: "Fill ANF-2A with business details" },
      { step: 3, title: "Document Upload", desc: "Upload ID, bank, and address proof" },
      { step: 4, title: "IEC Issued", desc: "Download e-IEC certificate" },
    ],
    faqs: [
      { q: "Is IEC renewal required?", a: "IEC doesn't need annual renewal. However, annual KYC updation is mandatory to keep it active." },
      { q: "Who needs an IEC?", a: "Any person or company importing/exporting goods (except personal use goods) must have an IEC." },
    ],
    relatedServices: ["gst-registration", "private-limited-company", "fssai-license"],
  },
  {
    id: "23",
    slug: "shop-establishment",
    category: "licenses",
    name: "Shop & Establishment Registration",
    icon: "🏪",
    shortDescription: "Register your shop or commercial establishment under the Shops and Establishment Act of your state.",
    description: "State-wise Shop and Establishment Act registration — mandatory for all shops, offices, warehouses, and commercial premises.",
    price: 1499,
    originalPrice: 2499,
    timeline: "3-5 working days",
    badge: "State License",
    seoTitle: "Shop & Establishment Registration India | dlegaltech",
    seoDescription: "Shop & Establishment registration starting at ₹1,499. State-wise compliance for shops, offices & commercial premises.",
    benefits: ["Legal Business Identity", "Employee Benefits Compliance", "Avoid Penalties", "Bank Account Support", "Local Compliance"],
    documents: ["Owner ID & Address Proof", "Business Premises Proof", "Business Name Details", "Nature of Business"],
    process: [
      { step: 1, title: "State Portal", desc: "Access state labour portal" },
      { step: 2, title: "Form Submission", desc: "Submit Form A with business details" },
      { step: 3, title: "Fee Payment", desc: "Pay registration fee based on employees" },
      { step: 4, title: "Certificate Issued", desc: "Receive establishment registration certificate" },
    ],
    faqs: [
      { q: "When should Shop Act be obtained?", a: "It must be obtained within 30 days of starting business. Each state has its own Shops & Establishments Act." },
      { q: "Is Shop Act registration annual?", a: "It needs annual renewal in most states. Failure to renew attracts penalties." },
    ],
    relatedServices: ["gst-registration", "msme-udyam", "fssai-license"],
  },
  // ── Legal Services ──
  {
    id: "24",
    slug: "legal-notice",
    category: "legal",
    name: "Legal Notice",
    icon: "📮",
    shortDescription: "Send a professionally drafted legal notice for debt recovery, breach of contract, property disputes, and more.",
    description: "Expert legal notice drafting and sending by registered advocates for civil, commercial, property, and employment disputes.",
    price: 1999,
    originalPrice: 3499,
    timeline: "1-2 working days",
    badge: "Quick Dispatch",
    seoTitle: "Legal Notice Drafting India | dlegaltech",
    seoDescription: "Professional legal notice starting at ₹1,999. Debt recovery, contract breach, property disputes. Sent by registered advocates.",
    benefits: ["Professional Drafting", "Legal Authority", "Dispute Resolution", "Evidence Record", "Cost Effective"],
    documents: ["Your ID Proof", "Correspondence History", "Contract/Agreement (if any)", "Evidence of Dispute"],
    process: [
      { step: 1, title: "Consultation", desc: "Discuss facts and relief sought" },
      { step: 2, title: "Notice Drafting", desc: "Draft legally sound notice" },
      { step: 3, title: "Review & Approval", desc: "Client review and finalization" },
      { step: 4, title: "Dispatch", desc: "Send via registered post/email" },
    ],
    faqs: [
      { q: "When should I send a legal notice?", a: "Before filing a court case, you should typically send a legal notice as it establishes your claim and gives the other party a chance to settle." },
      { q: "Is it mandatory to send a legal notice before suing?", a: "For cheque bounce cases under Section 138 NI Act, legal notice is mandatory. For most civil cases, it is advisable though not mandatory." },
    ],
    relatedServices: ["agreement-drafting", "trademark-registration", "private-limited-company"],
  },
  {
    id: "25",
    slug: "agreement-drafting",
    category: "legal",
    name: "Agreement / Contract Drafting",
    icon: "📃",
    shortDescription: "Professional drafting of business agreements, MOUs, NDAs, service contracts, and employment agreements.",
    description: "Legally vetted agreement drafting for all business needs — vendor contracts, employment, franchise, joint venture, and more.",
    price: 2999,
    originalPrice: 4999,
    timeline: "2-3 working days",
    badge: "Legally Vetted",
    seoTitle: "Agreement Contract Drafting India | dlegaltech",
    seoDescription: "Professional agreement drafting from ₹2,999. MOU, NDA, vendor, employment, franchise contracts by legal experts.",
    benefits: ["Legally Sound", "Dispute Prevention", "Custom Clauses", "Stamp Duty Guidance", "Notarization Support"],
    documents: ["Party Details", "Agreement Purpose", "Key Terms & Conditions", "Duration and Termination Terms"],
    process: [
      { step: 1, title: "Requirements Gathering", desc: "Understand parties, purpose, and key terms" },
      { step: 2, title: "Draft Preparation", desc: "Prepare agreement with all necessary clauses" },
      { step: 3, title: "Review Cycle", desc: "Client review and revisions (up to 2 rounds)" },
      { step: 4, title: "Finalization", desc: "Final agreement with stamp duty guidance" },
    ],
    faqs: [
      { q: "What types of agreements can you draft?", a: "Business agreements, employment contracts, vendor agreements, MOUs, NDAs, franchise agreements, lease deeds, joint venture agreements, and more." },
      { q: "Is stamp duty required on agreements?", a: "Yes, most agreements require stamp duty under the Indian Stamp Act. We guide you on the applicable stamp duty for your state and agreement type." },
    ],
    relatedServices: ["legal-notice", "trademark-registration", "private-limited-company"],
  },
  {
    id: "26",
    slug: "company-registration",
    category: "business",
    name: "Company Registration",
    icon: "🏢",
    shortDescription: "Register your company — Private Limited, OPC, LLP, Partnership, Section 8 with complete MCA compliance.",
    description: "Complete company incorporation services for Private Limited Company, One Person Company, Limited Liability Partnership, and more.",
    price: 5999,
    originalPrice: 8999,
    timeline: "10-15 working days",
    badge: "MCA Compliant",
    seoTitle: "Company Registration Online India | dlegaltech",
    seoDescription: "Register your company online starting at ₹5,999. Pvt Ltd, OPC, LLP, Section 8 registration with MCA. Expert assistance.",
    benefits: ["Separate Legal Entity", "Limited Liability", "Easy Funding", "Tax Benefits", "Brand Credibility"],
    documents: ["Director PAN & Aadhar", "Address Proof", "Registered Office Proof", "MOA & AOA Draft", "DSC Application"],
    process: [
      { step: 1, title: "Name Reservation", desc: "Apply for company name via RUN/SPICE+" },
      { step: 2, title: "DIN & DSC", desc: "Obtain Director Identification Numbers" },
      { step: 3, title: "Incorporation Filing", desc: "File SPICe+ form with MCA" },
      { step: 4, title: "CoI Issued", desc: "Certificate of Incorporation from MCA" },
    ],
    faqs: [
      { q: "What is the minimum capital for Pvt Ltd?", a: "There is no minimum paid-up capital requirement for Private Limited Company registration in India." },
      { q: "How many directors are needed?", a: "Minimum 2 directors are required for a Private Limited Company, with at least one being a resident Indian." },
    ],
    relatedServices: ["gst-registration", "trademark-registration", "section-8-company"],
  },
];

// ─── MEGA NAVIGATION ───────────────────────────────────────────────────────

export const MEGA_NAV = [
  {
    label: "NGO / Non-Profit",
    navLabel: "NGO Services",
    icon: "🏛️",
    href: "/services#ngo",
    color: "from-blue-600 to-blue-800",
    groups: [
      {
        title: "NGO Registration",
        items: [
          { label: "NGO / Trust Registration", href: "/services/ngo-registration", icon: "🏛️", badge: "Popular" },
          { label: "Society Registration", href: "/services/ngo-registration", icon: "👥" },
          { label: "Section 8 Company", href: "/services/section-8-company", icon: "🏢", badge: "Credible" },
          { label: "NITI Aayog (Darpan)", href: "/services/niti-aayog-registration", icon: "🏅" },
        ],
      },
      {
        title: "Tax & Funding",
        items: [
          { label: "12A & 80G Registration", href: "/services/12a-80g-registration", icon: "📋", badge: "Tax Benefit" },
          { label: "FCRA Registration", href: "/services/fcra-registration", icon: "🌐" },
          { label: "CSR Funding Assistance", href: "/services/csr-funding", icon: "💰" },
          { label: "Pan India NGO Services", href: "/locations", icon: "📍" },
        ],
      },
    ],
    featured: {
      title: "NGO Registration",
      desc: "Register your NGO/Trust and unlock government grants, tax exemptions, and CSR funding access.",
      href: "/services/ngo-registration",
      stat: "5,000+ NGOs Registered",
    },
  },
  {
    label: "Start a Business",
    navLabel: "Business",
    icon: "🚀",
    href: "/services#business",
    color: "from-amber-500 to-orange-600",
    groups: [
      {
        title: "Company Registration",
        items: [
          { label: "Private Limited Company", href: "/services/private-limited-company", icon: "🏗️", badge: "Popular" },
          { label: "One Person Company (OPC)", href: "/services/opc-registration", icon: "👤" },
          { label: "LLP Registration", href: "/services/llp-registration", icon: "🤝" },
          { label: "Partnership Firm", href: "/services/partnership-firm", icon: "📑" },
        ],
      },
      {
        title: "Startup & MSME",
        items: [
          { label: "Startup India (DPIIT)", href: "/services/startup-india", icon: "🚀", badge: "Tax Free 3yr" },
          { label: "Sole Proprietorship", href: "/services/sole-proprietorship", icon: "🧑‍💼" },
          { label: "MSME / Udyam", href: "/services/msme-udyam", icon: "🏭" },
          { label: "Nidhi Company", href: "/services/company-registration", icon: "🏦" },
        ],
      },
    ],
    featured: {
      title: "Start Your Business",
      desc: "₹5,999 all-inclusive company registration. Name, DIN, DSC, MCA filing & CoI — done in 10 days.",
      href: "/services/private-limited-company",
      stat: "10-day delivery",
    },
  },
  {
    label: "Tax & Compliance",
    navLabel: "Tax & GST",
    icon: "📊",
    href: "/services#tax",
    color: "from-green-600 to-emerald-700",
    groups: [
      {
        title: "GST Services",
        items: [
          { label: "GST Registration", href: "/services/gst-registration", icon: "📊", badge: "3-5 Days" },
          { label: "GST Return Filing", href: "/services/gst-return-filing", icon: "📝" },
          { label: "GST Annual Return", href: "/services/gst-return-filing", icon: "📅" },
          { label: "GST Cancellation", href: "/services/gst-registration", icon: "❌" },
        ],
      },
      {
        title: "Income Tax",
        items: [
          { label: "ITR Filing — Individual", href: "/services/income-tax-return", icon: "🧾" },
          { label: "ITR Filing — Business", href: "/services/income-tax-return", icon: "🏢" },
          { label: "TDS Return Filing", href: "/services/income-tax-return", icon: "💹" },
          { label: "MSME / Udyam", href: "/services/msme-udyam", icon: "🏭", badge: "Benefits" },
        ],
      },
    ],
    featured: {
      title: "GST Registration",
      desc: "Get GSTIN in 3-5 days. Input tax credit, interstate trade, legal business recognition.",
      href: "/services/gst-registration",
      stat: "₹1,499 onwards",
    },
  },
  {
    label: "Trademark & IP",
    navLabel: "Trademark",
    icon: "™️",
    href: "/services#ip",
    color: "from-purple-600 to-violet-700",
    groups: [
      {
        title: "Trademark Services",
        items: [
          { label: "Trademark Registration", href: "/services/trademark-registration", icon: "™️", badge: "Brand Guard" },
          { label: "Trademark Objection Reply", href: "/services/trademark-objection", icon: "⚖️" },
          { label: "Trademark Renewal", href: "/services/trademark-registration", icon: "🔄" },
          { label: "Trademark Assignment", href: "/services/trademark-registration", icon: "🔁" },
        ],
      },
      {
        title: "IP Protection",
        items: [
          { label: "Copyright Registration", href: "/services/copyright-registration", icon: "©️" },
          { label: "Patent Filing", href: "/services/patent-filing", icon: "🔬", badge: "20yr Protection" },
          { label: "Design Registration", href: "/services/trademark-registration", icon: "🎨" },
          { label: "Geographical Indication", href: "/services/trademark-registration", icon: "🗺️" },
        ],
      },
    ],
    featured: {
      title: "Trademark Registration",
      desc: "Use ™ symbol from Day 1. Protect your brand name, logo & tagline under Trade Marks Act 1999.",
      href: "/services/trademark-registration",
      stat: "₹5,999 onwards",
    },
  },
  {
    label: "Licenses & Permits",
    navLabel: "Licenses",
    icon: "📜",
    href: "/services#licenses",
    color: "from-teal-500 to-cyan-700",
    groups: [
      {
        title: "Business Licenses",
        items: [
          { label: "FSSAI Food License", href: "/services/fssai-license", icon: "🍎", badge: "Food Business" },
          { label: "Import Export Code (IEC)", href: "/services/iec-code", icon: "✈️" },
          { label: "Shop & Establishment", href: "/services/shop-establishment", icon: "🏪" },
          { label: "Drug License", href: "/services/fssai-license", icon: "💊" },
        ],
      },
      {
        title: "Certifications",
        items: [
          { label: "ISO Certification", href: "/services/company-registration", icon: "📋" },
          { label: "NSIC Registration", href: "/services/msme-udyam", icon: "🏭" },
          { label: "ESI / PF Registration", href: "/services/shop-establishment", icon: "👷" },
          { label: "Professional Tax (PT)", href: "/services/gst-registration", icon: "💼" },
        ],
      },
    ],
    featured: {
      title: "FSSAI Food License",
      desc: "Mandatory for all food businesses. Basic, State & Central license with full compliance support.",
      href: "/services/fssai-license",
      stat: "₹1,999 onwards",
    },
  },
  {
    label: "Legal Services",
    navLabel: "Legal",
    icon: "⚖️",
    href: "/services#legal",
    color: "from-rose-600 to-red-700",
    groups: [
      {
        title: "Legal Documents",
        items: [
          { label: "Legal Notice", href: "/services/legal-notice", icon: "📮" },
          { label: "Agreement / Contract", href: "/services/agreement-drafting", icon: "📃", badge: "Vetted" },
          { label: "MOU / NDA Drafting", href: "/services/agreement-drafting", icon: "🤝" },
          { label: "Power of Attorney", href: "/services/agreement-drafting", icon: "📝" },
        ],
      },
      {
        title: "Personal Legal",
        items: [
          { label: "Will / Testament Drafting", href: "/services/agreement-drafting", icon: "📜" },
          { label: "Rent Agreement", href: "/services/agreement-drafting", icon: "🏠" },
          { label: "Affidavit Drafting", href: "/services/legal-notice", icon: "✍️" },
          { label: "Name Change Affidavit", href: "/services/legal-notice", icon: "👤" },
        ],
      },
    ],
    featured: {
      title: "Legal Agreements",
      desc: "Legally vetted business agreements, contracts, MOUs and NDAs crafted by experienced advocates.",
      href: "/services/agreement-drafting",
      stat: "₹2,999 onwards",
    },
  },
];

// ─── LOCATIONS ──────────────────────────────────────────────────────────────

export const LOCATIONS = [
  {
    slug: "ranchi",
    city: "Ranchi",
    state: "Jharkhand",
    stateCode: "JH",
    lat: 23.3441,
    lng: 85.3096,
    pincode: "834001",
    phone: "+91-8603456708",
    address: "Lalpur, Ranchi, Jharkhand - 834001",
    description: "Serving NGOs and businesses in Ranchi and across Jharkhand with expert legal consultancy.",
    localKeyword: "Jharkhand NGO Registration",
  },
  {
    slug: "prayagraj",
    city: "Prayagraj",
    state: "Uttar Pradesh",
    stateCode: "UP",
    lat: 25.4358,
    lng: 81.8463,
    pincode: "211001",
    phone: "+91-8603456708",
    address: "Civil Lines, Prayagraj, Uttar Pradesh - 211001",
    description: "Expert NGO and business registration services in Prayagraj and surrounding UP districts.",
    localKeyword: "UP NGO Registration Prayagraj",
  },
  {
    slug: "pune",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "MH",
    lat: 18.5204,
    lng: 73.8567,
    pincode: "411001",
    phone: "+91-8603456708",
    address: "Shivajinagar, Pune, Maharashtra - 411001",
    description: "Trusted legal consultancy for startups and NGOs in Pune and entire Maharashtra.",
    localKeyword: "NGO Registration Pune Maharashtra",
  },
  {
    slug: "patna",
    city: "Patna",
    state: "Bihar",
    stateCode: "BR",
    lat: 25.5941,
    lng: 85.1376,
    pincode: "800001",
    phone: "+91-8603456708",
    address: "Boring Road, Patna, Bihar - 800001",
    description: "Complete NGO registration and legal services in Patna and across Bihar.",
    localKeyword: "NGO Registration Patna Bihar",
  },
  {
    slug: "delhi",
    city: "Delhi",
    state: "Delhi",
    stateCode: "DL",
    lat: 28.6139,
    lng: 77.2090,
    pincode: "110001",
    phone: "+91-8603456708",
    address: "Connaught Place, New Delhi - 110001",
    description: "Premium legal consultancy and NGO registration services across Delhi NCR.",
    localKeyword: "NGO Registration Delhi",
  },
  {
    slug: "mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "MH",
    lat: 19.0760,
    lng: 72.8777,
    pincode: "400001",
    phone: "+91-8603456708",
    address: "Fort, Mumbai, Maharashtra - 400001",
    description: "Expert business and NGO registration services for Mumbai's vibrant social sector.",
    localKeyword: "NGO Registration Mumbai",
  },
];

// ─── STATIC DATA ─────────────────────────────────────────────────────────────

export const STATS = [
  { value: "5000+", label: "Happy Clients", icon: "😊" },
  { value: "15+", label: "Years Experience", icon: "🏆" },
  { value: "98%", label: "Success Rate", icon: "✅" },
  { value: "4.9★", label: "Google Rating", icon: "⭐" },
];

export const TESTIMONIALS = [
  {
    name: "Rajesh Kumar",
    role: "NGO Founder",
    location: "Ranchi, Jharkhand",
    rating: 5,
    text: "dlegaltech made our NGO registration incredibly smooth. Their expert team guided us at every step. Got our trust registered and 12A certificate within the promised timeline!",
    initials: "RK",
  },
  {
    name: "Priya Sharma",
    role: "Social Entrepreneur",
    location: "Prayagraj, UP",
    rating: 5,
    text: "Exceptional service! They handled our Section 8 Company registration and FCRA application end-to-end. Very professional and transparent about fees. Highly recommend.",
    initials: "PS",
  },
  {
    name: "Mohammed Arif",
    role: "Startup Founder",
    location: "Pune, Maharashtra",
    rating: 5,
    text: "Got my company registered and trademark filed in record time. The team is responsive on WhatsApp which is very convenient. Will use their GST compliance services too.",
    initials: "MA",
  },
  {
    name: "Anita Singh",
    role: "NGO Director",
    location: "Patna, Bihar",
    rating: 5,
    text: "The CSR funding assistance they provided connected us with 3 corporates. The proposal writing quality is excellent. We received ₹15 lakhs in CSR funding last year!",
    initials: "AS",
  },
  {
    name: "Suresh Pandey",
    role: "Chartered Accountant",
    location: "Delhi",
    rating: 5,
    text: "I refer all my NGO clients to dlegaltech. Fast turnaround, proper documentation, and they stay updated on latest legal changes. Partners like these make our job easier.",
    initials: "SP",
  },
  {
    name: "Dr. Kavita Mehra",
    role: "Education NGO",
    location: "Mumbai",
    rating: 5,
    text: "From NGO registration to FCRA to 80G — they handled everything. Even helped with our CSR-1 filing. The tracking dashboard kept us informed at every stage. Top-notch!",
    initials: "KM",
  },
];

export const BLOG_POSTS = [
  {
    slug: "ngo-registration-complete-guide-india-2024",
    title: "Complete Guide to NGO Registration in India 2024",
    excerpt: "Everything you need to know about registering an NGO in India — Trust, Society, Section 8 Company comparison, documents required, and timeline.",
    category: "NGO Guide",
    author: "dlegaltech Legal Team",
    date: "2024-12-15",
    readTime: "8 min read",
    image: "/blog/ngo-guide.jpg",
    tags: ["NGO Registration", "Trust", "Society", "Section 8"],
  },
  {
    slug: "12a-80g-registration-tax-benefits-ngo",
    title: "12A & 80G Registration: Complete Tax Benefits Guide for NGOs",
    excerpt: "How to get 12A and 80G tax exemption for your NGO, attract more donations, and access government grants. Step-by-step filing guide.",
    category: "Tax & Compliance",
    author: "dlegaltech Legal Team",
    date: "2024-11-28",
    readTime: "6 min read",
    image: "/blog/tax-guide.jpg",
    tags: ["12A", "80G", "Tax Exemption", "NGO"],
  },
  {
    slug: "fcra-registration-guide-foreign-donations",
    title: "FCRA Registration Guide: How to Legally Receive Foreign Donations",
    excerpt: "Complete FCRA registration process, eligibility criteria, required documents, and compliance requirements for Indian NGOs to receive foreign funding.",
    category: "Legal Updates",
    author: "dlegaltech Legal Team",
    date: "2024-11-10",
    readTime: "10 min read",
    image: "/blog/fcra-guide.jpg",
    tags: ["FCRA", "Foreign Donations", "NGO", "Compliance"],
  },
  {
    slug: "csr-funding-how-ngos-apply",
    title: "CSR Funding for NGOs: How to Apply and Get Corporate Grants",
    excerpt: "Step-by-step guide to CSR-1 registration, identifying CSR donors, writing compelling proposals, and securing corporate social responsibility funding.",
    category: "Funding & Grants",
    author: "dlegaltech Legal Team",
    date: "2024-10-22",
    readTime: "7 min read",
    image: "/blog/csr-guide.jpg",
    tags: ["CSR Funding", "Corporate Grants", "NGO", "CSR-1"],
  },
  {
    slug: "section-8-company-vs-trust-vs-society",
    title: "Section 8 Company vs Trust vs Society: Which is Better for Your NGO?",
    excerpt: "Comprehensive comparison of three NGO structures in India — their advantages, disadvantages, registration process, and which one suits your needs.",
    category: "NGO Guide",
    author: "dlegaltech Legal Team",
    date: "2024-10-05",
    readTime: "9 min read",
    image: "/blog/comparison-guide.jpg",
    tags: ["Section 8", "Trust", "Society", "NGO Registration"],
  },
  {
    slug: "trademark-registration-brand-protection-india",
    title: "Trademark Registration in India: Protect Your Brand in 2024",
    excerpt: "Why trademark registration is crucial for your brand, the complete process, classes of goods/services, and how to respond to objections.",
    category: "Business",
    author: "dlegaltech Legal Team",
    date: "2024-09-18",
    readTime: "6 min read",
    image: "/blog/trademark-guide.jpg",
    tags: ["Trademark", "Brand Protection", "IPR", "Business"],
  },
];

export const PROCESS_STEPS = [
  {
    step: 1,
    title: "Choose Your Service",
    desc: "Browse our services and select what you need. Get instant price quotes.",
    icon: "🔍",
  },
  {
    step: 2,
    title: "Upload Documents",
    desc: "Upload required documents securely via our encrypted portal.",
    icon: "📁",
  },
  {
    step: 3,
    title: "Expert Review & Filing",
    desc: "Our legal experts review, process, and file your application.",
    icon: "⚖️",
  },
  {
    step: 4,
    title: "Receive Certificate",
    desc: "Get your official certificate and documents delivered digitally.",
    icon: "🎓",
  },
];

// Legacy compatibility for pages using NAV_LINKS
export const NAV_LINKS = MEGA_NAV.map((item) => ({
  label: item.label,
  href: item.href,
  dropdown: item.groups.flatMap((g) => g.items).map((i) => ({ label: i.label, href: i.href })),
}));
