export const BRAND = {
  name: "dlegaltech",
  fullName: "Sai NGO & Business Consultancy®️",
  tagline: "India's Most Trusted Digital Legal Consultancy Platform",
  founder: "Advocate P.R. Pandey",
  phone: "+91-8603456708",
  whatsapp: "918603456708",
  email: "saingoconsultancy@gmail.com",
  website: "https://www.dlegaltech.com",
  primaryColor: "#0A346C",
  accentColor: "#ED931A",
  trademark: "®️",
};

export const SERVICES = [
  {
    id: "1",
    slug: "ngo-registration",
    name: "NGO Registration",
    icon: "🏛️",
    shortDescription: "Register your NGO/Trust under the Societies Registration Act or Indian Trusts Act with complete compliance.",
    description: "Complete NGO registration services including Trust, Society, and Section 8 Company formation with all government compliance.",
    price: 4999,
    originalPrice: 7999,
    timeline: "7-10 working days",
    badge: "Most Popular",
    seoTitle: "NGO Registration Online India | Sai Consultancy",
    seoDescription: "Register your NGO online in India starting at ₹4,999. Trust, Society & Section 8 Company registration. Expert guidance by Advocate P.R. Pandey.",
    benefits: ["Certificate of Incorporation", "PAN & TAN Registration", "Bank Account Opening Support", "80G & 12A Guidance"],
    documents: ["Aadhar Card of all members", "PAN Card", "Address Proof", "Passport Size Photos", "Registered Office Address Proof"],
    process: [
      { step: 1, title: "Submit Application", desc: "Fill online form with member details" },
      { step: 2, title: "Document Review", desc: "Our experts verify all documents" },
      { step: 3, title: "Government Filing", desc: "We file with concerned authority" },
      { step: 4, title: "Certificate Issued", desc: "Receive digital certificate" },
    ],
    faqs: [
      { q: "What is the minimum number of members for NGO registration?", a: "For Society registration, minimum 7 members are required. For Trust, minimum 2 trustees are needed." },
      { q: "Can an NGO earn profit?", a: "No, NGOs cannot distribute profits among members. Any surplus must be used for the stated objectives." },
      { q: "How long does NGO registration take?", a: "Generally 7-10 working days after complete document submission and payment." },
    ],
    relatedServices: ["12a-80g-registration", "fcra-registration", "section-8-company"],
  },
  {
    id: "2",
    slug: "12a-80g-registration",
    name: "12A & 80G Registration",
    icon: "📋",
    shortDescription: "Get tax exemption for your NGO under Section 12A and enable donors to claim tax benefits under 80G.",
    description: "Secure tax exemption status for your NGO with 12A registration and attract more donations with 80G certification.",
    price: 3999,
    originalPrice: 5999,
    timeline: "30-45 working days",
    badge: "Tax Benefit",
    seoTitle: "12A 80G Registration Online India | Sai Consultancy",
    seoDescription: "Get NGO tax exemption with 12A & 80G registration starting at ₹3,999. Enable donors to claim 50% tax deduction. Expert assistance.",
    benefits: ["Income Tax Exemption", "Donor Tax Benefits", "Government Grants Eligibility", "CSR Funding Access"],
    documents: ["NGO Registration Certificate", "Trust Deed / MoA", "Audited Financial Statements", "Activity Report", "PAN Card of NGO"],
    process: [
      { step: 1, title: "Eligibility Check", desc: "Verify NGO eligibility criteria" },
      { step: 2, title: "Application Prep", desc: "Prepare Form 10A/10AB" },
      { step: 3, title: "IT Department Filing", desc: "Submit to Income Tax authorities" },
      { step: 4, title: "Certificate Received", desc: "Get 12A & 80G certificates" },
    ],
    faqs: [
      { q: "What is the difference between 12A and 80G?", a: "12A gives tax exemption to the NGO itself on its income. 80G allows donors to claim tax deductions on their donations." },
      { q: "Is 12A registration mandatory for NGOs?", a: "Not mandatory, but highly recommended as it exempts NGO income from tax and makes the organization eligible for government grants." },
    ],
    relatedServices: ["ngo-registration", "fcra-registration", "csr-funding"],
  },
  {
    id: "3",
    slug: "section-8-company",
    name: "Section 8 Company",
    icon: "🏢",
    shortDescription: "Incorporate a Section 8 Company (Non-Profit Organization) under Companies Act 2013 with MCA registration.",
    description: "Section 8 Company is the most credible form of NGO in India, regulated by MCA with highest transparency and governance.",
    price: 6999,
    originalPrice: 9999,
    timeline: "15-20 working days",
    badge: "High Credibility",
    seoTitle: "Section 8 Company Registration India | Sai Consultancy",
    seoDescription: "Register Section 8 Non-Profit Company online starting at ₹6,999. MCA registration, most credible NGO form in India.",
    benefits: ["MCA Registered", "Limited Liability", "No Minimum Capital", "Government Grant Eligible", "Foreign Funding (FCRA)"],
    documents: ["Director KYC (Aadhar + PAN)", "Address Proof of Directors", "Registered Office Proof", "Digital Signature Certificate (DSC)", "Objectives/MoA Draft"],
    process: [
      { step: 1, title: "Name Approval", desc: "Apply for company name via MCA portal" },
      { step: 2, title: "DIN & DSC", desc: "Director Identification Number & Digital Signature" },
      { step: 3, title: "MOA & AOA Filing", desc: "File incorporation documents with MCA" },
      { step: 4, title: "Certificate of Incorporation", desc: "Receive CoI from MCA" },
    ],
    faqs: [
      { q: "What is a Section 8 Company?", a: "A Section 8 Company is a non-profit organization incorporated under Section 8 of the Companies Act 2013, formed for promoting arts, science, sports, education, social welfare, etc." },
      { q: "Can a Section 8 Company receive foreign donations?", a: "Yes, after obtaining FCRA registration, a Section 8 Company can receive foreign contributions." },
    ],
    relatedServices: ["ngo-registration", "fcra-registration", "12a-80g-registration"],
  },
  {
    id: "4",
    slug: "fcra-registration",
    name: "FCRA Registration",
    icon: "🌐",
    shortDescription: "Get FCRA license to legally receive foreign contributions and donations for your NGO activities.",
    description: "Foreign Contribution (Regulation) Act registration to receive donations from foreign nationals, organizations, and governments.",
    price: 8999,
    originalPrice: 12999,
    timeline: "3-6 months",
    badge: "Foreign Funding",
    seoTitle: "FCRA Registration Online India | Sai Consultancy",
    seoDescription: "Get FCRA registration for your NGO to receive foreign donations legally. Complete assistance starting at ₹8,999.",
    benefits: ["Foreign Donation Legal", "FCRA Bank Account", "International Credibility", "Expanded Funding Sources"],
    documents: ["NGO Registration Certificate", "12A & 80G Certificates", "3 Year Audited Accounts", "Board Resolution", "Activity Report (Last 3 years)"],
    process: [
      { step: 1, title: "Eligibility Assessment", desc: "Verify 3-year existence and activities" },
      { step: 2, title: "Online Application", desc: "File FCRA application on MHA portal" },
      { step: 3, title: "Police Verification", desc: "Background check of key office bearers" },
      { step: 4, title: "FCRA Granted", desc: "Receive FCRA registration certificate" },
    ],
    faqs: [
      { q: "Who can apply for FCRA?", a: "NGOs that have been registered for at least 3 years and have spent minimum ₹15 lakh on activities can apply for FCRA." },
      { q: "What is the FCRA bank account requirement?", a: "All foreign contributions must be received in a designated FCRA bank account, typically at SBI New Delhi main branch." },
    ],
    relatedServices: ["ngo-registration", "12a-80g-registration", "section-8-company"],
  },
  {
    id: "5",
    slug: "gst-registration",
    name: "GST Registration",
    icon: "📊",
    shortDescription: "Register for Goods and Services Tax with hassle-free online process and get GSTIN within 3-5 days.",
    description: "Complete GST registration for businesses, NGOs, and professionals with ongoing compliance support.",
    price: 1499,
    originalPrice: 2499,
    timeline: "3-5 working days",
    badge: "Quick Process",
    seoTitle: "GST Registration Online India | Sai Consultancy",
    seoDescription: "Get GST registration online in 3-5 days starting at ₹1,499. Expert assistance for businesses, NGOs & professionals.",
    benefits: ["GSTIN Issued", "Input Tax Credit", "Legal Business Recognition", "Interstate Trade Enabled"],
    documents: ["Aadhar Card", "PAN Card", "Business Address Proof", "Bank Account Details", "Business Photographs"],
    process: [
      { step: 1, title: "Document Collection", desc: "Submit required KYC documents" },
      { step: 2, title: "Form Filling", desc: "File REG-01 on GST portal" },
      { step: 3, title: "ARN Generated", desc: "Application Reference Number issued" },
      { step: 4, title: "GSTIN Received", desc: "GST Identification Number issued" },
    ],
    faqs: [
      { q: "Who needs to register for GST?", a: "Businesses with turnover above ₹40 lakhs (₹20 lakhs for services) must register for GST. Inter-state suppliers must register regardless of turnover." },
      { q: "Is GST registration mandatory for NGOs?", a: "NGOs providing taxable services with turnover above threshold must register. Services like education, healthcare are generally exempt." },
    ],
    relatedServices: ["ngo-registration", "company-registration", "trademark-registration"],
  },
  {
    id: "6",
    slug: "trademark-registration",
    name: "Trademark Registration",
    icon: "™️",
    shortDescription: "Protect your brand identity with trademark registration under the Trade Marks Act 1999.",
    description: "Secure your brand name, logo, and tagline with trademark registration. Protect your intellectual property legally.",
    price: 5999,
    originalPrice: 8999,
    timeline: "1-2 years (final), TM symbol in 2-3 days",
    badge: "Brand Protection",
    seoTitle: "Trademark Registration Online India | Sai Consultancy",
    seoDescription: "Register your trademark online starting at ₹5,999. Protect brand name, logo & tagline. TM symbol usage from day 1.",
    benefits: ["Brand Protection", "Legal Rights", "TM Symbol Usage", "Infringement Action", "Asset Creation"],
    documents: ["Applicant ID Proof", "Logo/Brand Name (JPG)", "Goods/Services Description", "POA (Power of Attorney)", "MSME Certificate (if applicable)"],
    process: [
      { step: 1, title: "Trademark Search", desc: "Check availability and conflicts" },
      { step: 2, title: "Application Filing", desc: "File TM-A with IP India" },
      { step: 3, title: "TM Symbol Allowed", desc: "Use ™ immediately after filing" },
      { step: 4, title: "® Symbol", desc: "After registration approval (12-18 months)" },
    ],
    faqs: [
      { q: "How long does trademark registration take?", a: "After filing, you can use the ™ symbol immediately. Full ® registration takes 12-24 months subject to objections and oppositions." },
      { q: "What can be trademarked?", a: "Brand names, logos, taglines, product names, sounds, colors, and shapes can be registered as trademarks." },
    ],
    relatedServices: ["company-registration", "ngo-registration", "copyright-registration"],
  },
  {
    id: "7",
    slug: "company-registration",
    name: "Company Registration",
    icon: "🏗️",
    shortDescription: "Register your Private Limited Company, OPC, or LLP with MCA. Fast, affordable, expert-guided process.",
    description: "Complete company incorporation services for Private Limited Company, One Person Company, Limited Liability Partnership, and more.",
    price: 5999,
    originalPrice: 8999,
    timeline: "10-15 working days",
    badge: "Most Trusted",
    seoTitle: "Company Registration Online India | Sai Consultancy",
    seoDescription: "Register your company online starting at ₹5,999. Pvt Ltd, OPC, LLP registration with MCA. Expert assistance.",
    benefits: ["Separate Legal Entity", "Limited Liability", "Easy Funding", "Tax Benefits", "Brand Credibility"],
    documents: ["Director PAN & Aadhar", "Address Proof", "Registered Office Proof", "MOA & AOA Draft", "DSC Application"],
    process: [
      { step: 1, title: "Name Reservation", desc: "Apply for company name via RUN/SPICE+" },
      { step: 2, title: "DIN & DSC", desc: "Obtain Director Identification Numbers" },
      { step: 3, title: "Incorporation Filing", desc: "File SPICe+ form with MCA" },
      { step: 4, title: "CoI Issued", desc: "Certificate of Incorporation from MCA" },
    ],
    faqs: [
      { q: "What is the minimum capital for Pvt Ltd?", a: "There is no minimum paid-up capital requirement for Private Limited Company registration in India." },
      { q: "How many directors are needed?", a: "Minimum 2 directors are required for a Private Limited Company, with at least one being a resident Indian." },
    ],
    relatedServices: ["gst-registration", "trademark-registration", "section-8-company"],
  },
  {
    id: "8",
    slug: "csr-funding",
    name: "CSR Funding Assistance",
    icon: "💰",
    shortDescription: "Connect your NGO with corporates for CSR funding. End-to-end proposal writing and compliance support.",
    description: "Complete CSR funding assistance — from identifying potential donors to writing compelling proposals and maintaining compliance.",
    price: 9999,
    originalPrice: 14999,
    timeline: "Ongoing service",
    badge: "High Value",
    seoTitle: "CSR Funding for NGO India | Sai Consultancy",
    seoDescription: "Get CSR funding for your NGO. Expert proposal writing, corporate matching, and compliance support. Connect with 500+ CSR donors.",
    benefits: ["Corporate Connections", "Proposal Writing", "CSR Compliance", "Form CSR-1 Filing", "Impact Reporting"],
    documents: ["NGO Registration", "12A & 80G Certificates", "FCRA (if applicable)", "Audited Accounts", "Project Proposal"],
    process: [
      { step: 1, title: "NGO Profile Creation", desc: "Create compelling NGO dossier" },
      { step: 2, title: "CSR-1 Filing", desc: "Register on MCA CSR portal" },
      { step: 3, title: "Corporate Matching", desc: "Connect with relevant CSR committees" },
      { step: 4, title: "Proposal & Follow-up", desc: "Submit and track applications" },
    ],
    faqs: [
      { q: "What is CSR-1 form?", a: "CSR-1 is a mandatory form for NGOs to register on the MCA portal to receive CSR funds from companies. It establishes the NGO's credibility." },
      { q: "Which companies provide CSR funding?", a: "Companies with net worth ≥₹500 crore, or turnover ≥₹1000 crore, or net profit ≥₹5 crore must spend 2% of average net profit on CSR." },
    ],
    relatedServices: ["ngo-registration", "12a-80g-registration", "fcra-registration"],
  },
];

export const LOCATIONS = [
  {
    slug: "ranchi",
    city: "Ranchi",
    state: "Jharkhand",
    stateCode: "JH",
    lat: 23.3441,
    lng: 85.3096,
    pincode: "834001",
    phone: "+91-8603456708",
    address: "Lalpur, Ranchi, Jharkhand - 834001",
    description: "Serving NGOs and businesses in Ranchi and across Jharkhand with expert legal consultancy.",
    localKeyword: "Jharkhand NGO Registration",
  },
  {
    slug: "prayagraj",
    city: "Prayagraj",
    state: "Uttar Pradesh",
    stateCode: "UP",
    lat: 25.4358,
    lng: 81.8463,
    pincode: "211001",
    phone: "+91-8603456708",
    address: "Civil Lines, Prayagraj, Uttar Pradesh - 211001",
    description: "Expert NGO and business registration services in Prayagraj and surrounding UP districts.",
    localKeyword: "UP NGO Registration Prayagraj",
  },
  {
    slug: "pune",
    city: "Pune",
    state: "Maharashtra",
    stateCode: "MH",
    lat: 18.5204,
    lng: 73.8567,
    pincode: "411001",
    phone: "+91-8603456708",
    address: "Shivajinagar, Pune, Maharashtra - 411001",
    description: "Trusted legal consultancy for startups and NGOs in Pune and entire Maharashtra.",
    localKeyword: "NGO Registration Pune Maharashtra",
  },
  {
    slug: "patna",
    city: "Patna",
    state: "Bihar",
    stateCode: "BR",
    lat: 25.5941,
    lng: 85.1376,
    pincode: "800001",
    phone: "+91-8603456708",
    address: "Boring Road, Patna, Bihar - 800001",
    description: "Complete NGO registration and legal services in Patna and across Bihar.",
    localKeyword: "NGO Registration Patna Bihar",
  },
  {
    slug: "delhi",
    city: "Delhi",
    state: "Delhi",
    stateCode: "DL",
    lat: 28.6139,
    lng: 77.2090,
    pincode: "110001",
    phone: "+91-8603456708",
    address: "Connaught Place, New Delhi - 110001",
    description: "Premium legal consultancy and NGO registration services across Delhi NCR.",
    localKeyword: "NGO Registration Delhi",
  },
  {
    slug: "mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    stateCode: "MH",
    lat: 19.0760,
    lng: 72.8777,
    pincode: "400001",
    phone: "+91-8603456708",
    address: "Fort, Mumbai, Maharashtra - 400001",
    description: "Expert business and NGO registration services for Mumbai's vibrant social sector.",
    localKeyword: "NGO Registration Mumbai",
  },
];

export const STATS = [
  { value: "5000+", label: "Happy Clients", icon: "😊" },
  { value: "15+", label: "Years Experience", icon: "🏆" },
  { value: "98%", label: "Success Rate", icon: "✅" },
  { value: "4.9★", label: "Google Rating", icon: "⭐" },
];

export const TESTIMONIALS = [
  {
    name: "Rajesh Kumar",
    role: "NGO Founder",
    location: "Ranchi, Jharkhand",
    rating: 5,
    text: "Sai NGO Consultancy made our NGO registration incredibly smooth. Advocate P.R. Pandey's team guided us at every step. Got our trust registered and 12A certificate within the promised timeline!",
    initials: "RK",
  },
  {
    name: "Priya Sharma",
    role: "Social Entrepreneur",
    location: "Prayagraj, UP",
    rating: 5,
    text: "Exceptional service! They handled our Section 8 Company registration and FCRA application end-to-end. Very professional and transparent about fees. Highly recommend for NGO work.",
    initials: "PS",
  },
  {
    name: "Mohammed Arif",
    role: "Startup Founder",
    location: "Pune, Maharashtra",
    rating: 5,
    text: "Got my company registered and trademark filed in record time. The team is responsive on WhatsApp which is very convenient. Will use their GST compliance services too.",
    initials: "MA",
  },
  {
    name: "Anita Singh",
    role: "NGO Director",
    location: "Patna, Bihar",
    rating: 5,
    text: "The CSR funding assistance they provided connected us with 3 corporates. The proposal writing quality is excellent. We received ₹15 lakhs in CSR funding last year!",
    initials: "AS",
  },
  {
    name: "Suresh Pandey",
    role: "Chartered Accountant",
    location: "Delhi",
    rating: 5,
    text: "I refer all my NGO clients to Sai NGO Consultancy. Fast turnaround, proper documentation, and they stay updated on latest legal changes. Partners like these make our job easier.",
    initials: "SP",
  },
  {
    name: "Dr. Kavita Mehra",
    role: "Education NGO",
    location: "Mumbai",
    rating: 5,
    text: "From NGO registration to FCRA to 80G — they handled everything. Even helped with our CSR-1 filing. The tracking dashboard kept us informed at every stage. Top-notch!",
    initials: "KM",
  },
];

export const BLOG_POSTS = [
  {
    slug: "ngo-registration-complete-guide-india-2024",
    title: "Complete Guide to NGO Registration in India 2024",
    excerpt: "Everything you need to know about registering an NGO in India — Trust, Society, Section 8 Company comparison, documents required, and timeline.",
    category: "NGO Guide",
    author: "Advocate P.R. Pandey",
    date: "2024-12-15",
    readTime: "8 min read",
    image: "/blog/ngo-guide.jpg",
    tags: ["NGO Registration", "Trust", "Society", "Section 8"],
  },
  {
    slug: "12a-80g-registration-tax-benefits-ngo",
    title: "12A & 80G Registration: Complete Tax Benefits Guide for NGOs",
    excerpt: "How to get 12A and 80G tax exemption for your NGO, attract more donations, and access government grants. Step-by-step filing guide.",
    category: "Tax & Compliance",
    author: "Advocate P.R. Pandey",
    date: "2024-11-28",
    readTime: "6 min read",
    image: "/blog/tax-guide.jpg",
    tags: ["12A", "80G", "Tax Exemption", "NGO"],
  },
  {
    slug: "fcra-registration-guide-foreign-donations",
    title: "FCRA Registration Guide: How to Legally Receive Foreign Donations",
    excerpt: "Complete FCRA registration process, eligibility criteria, required documents, and compliance requirements for Indian NGOs to receive foreign funding.",
    category: "Legal Updates",
    author: "Advocate P.R. Pandey",
    date: "2024-11-10",
    readTime: "10 min read",
    image: "/blog/fcra-guide.jpg",
    tags: ["FCRA", "Foreign Donations", "NGO", "Compliance"],
  },
  {
    slug: "csr-funding-how-ngos-apply",
    title: "CSR Funding for NGOs: How to Apply and Get Corporate Grants",
    excerpt: "Step-by-step guide to CSR-1 registration, identifying CSR donors, writing compelling proposals, and securing corporate social responsibility funding.",
    category: "Funding & Grants",
    author: "Advocate P.R. Pandey",
    date: "2024-10-22",
    readTime: "7 min read",
    image: "/blog/csr-guide.jpg",
    tags: ["CSR Funding", "Corporate Grants", "NGO", "CSR-1"],
  },
  {
    slug: "section-8-company-vs-trust-vs-society",
    title: "Section 8 Company vs Trust vs Society: Which is Better for Your NGO?",
    excerpt: "Comprehensive comparison of three NGO structures in India — their advantages, disadvantages, registration process, and which one suits your needs.",
    category: "NGO Guide",
    author: "Advocate P.R. Pandey",
    date: "2024-10-05",
    readTime: "9 min read",
    image: "/blog/comparison-guide.jpg",
    tags: ["Section 8", "Trust", "Society", "NGO Registration"],
  },
  {
    slug: "trademark-registration-brand-protection-india",
    title: "Trademark Registration in India: Protect Your Brand in 2024",
    excerpt: "Why trademark registration is crucial for your brand, the complete process, classes of goods/services, and how to respond to objections.",
    category: "Business",
    author: "Advocate P.R. Pandey",
    date: "2024-09-18",
    readTime: "6 min read",
    image: "/blog/trademark-guide.jpg",
    tags: ["Trademark", "Brand Protection", "IPR", "Business"],
  },
];

export const PROCESS_STEPS = [
  {
    step: 1,
    title: "Choose Your Service",
    desc: "Browse our services and select what you need. Get instant price quotes.",
    icon: "🔍",
  },
  {
    step: 2,
    title: "Upload Documents",
    desc: "Upload required documents securely via our encrypted portal.",
    icon: "📁",
  },
  {
    step: 3,
    title: "Expert Review & Filing",
    desc: "Our legal experts review, process, and file your application.",
    icon: "⚖️",
  },
  {
    step: 4,
    title: "Receive Certificate",
    desc: "Get your official certificate and documents delivered digitally.",
    icon: "🎓",
  },
];

export const NAV_LINKS = [
  {
    label: "Services",
    href: "/services",
    dropdown: [
      { label: "NGO Registration", href: "/services/ngo-registration" },
      { label: "12A & 80G Registration", href: "/services/12a-80g-registration" },
      { label: "Section 8 Company", href: "/services/section-8-company" },
      { label: "FCRA Registration", href: "/services/fcra-registration" },
      { label: "GST Registration", href: "/services/gst-registration" },
      { label: "Trademark Registration", href: "/services/trademark-registration" },
      { label: "Company Registration", href: "/services/company-registration" },
      { label: "CSR Funding Assistance", href: "/services/csr-funding" },
    ],
  },
  {
    label: "Locations",
    href: "/locations",
    dropdown: LOCATIONS.map((l) => ({
      label: `${l.city}, ${l.stateCode}`,
      href: `/locations/${l.slug}`,
    })),
  },
  { label: "Blog", href: "/blog" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];
